import type { CultureKey, Params, RuleDef, RuleFx, RuleId, RuleTheme } from "./types";

export const DEFAULT_PARAMS: Params = {
  money: true,
  workHours: 8,
  ubi: 0,
  ads: true,
  internet: true,
  wasteTax: false,
  sharedProperty: false,
  voting: false,
  rewards: false,
  mandatoryHelp: false,
  mandatoryTree: false,
  outsideHour: false,
  skillQuota: false,
  noLying: false,
  mustAnswer: false,
};

export const RULES: RuleDef[] = [
  {
    id: "no-lying",
    theme: "civic",
    num: 1,
    title: "Nobody May Lie",
    flavor: "Every statement, public or private, must be true.",
    pressures: ["Honesty", "Advertising", "Politics"],
    params: { noLying: true },
    push: { honesty: 14 },
  },
  {
    id: "help-stranger",
    theme: "social",
    num: 2,
    title: "Everyone Must Help One Stranger Each Day",
    flavor: "One act of help, every day, for someone you don't know.",
    pressures: ["Kindness", "Obligation"],
    params: { mandatoryHelp: true },
    push: { generosity: 10, community: 5 },
  },
  {
    id: "no-money",
    theme: "money",
    num: 3,
    title: "No Money",
    flavor: "Currency is abolished. Exchange however you can.",
    pressures: ["Commerce", "Reputation"],
    params: { money: false },
    push: { reputation: 12, equality: 6 },
    unlock: { key: "reputation", min: 56, hint: "a city where reputation starts to matter" },
  },
  {
    id: "four-hour-day",
    theme: "work",
    num: 4,
    title: "Everyone Works Only Four Hours",
    flavor: "The workday ends at lunch.",
    pressures: ["Labor", "Free time"],
    params: { workHours: 4 },
    push: { leisure: 14 },
  },
  {
    id: "basic-income",
    theme: "money",
    num: 5,
    title: "Everyone Gets the Same Basic Income",
    flavor: "An equal payment lands in every account each morning.",
    pressures: ["Income", "Work incentives"],
    params: { ubi: 14 },
    push: { equality: 10 },
  },
  {
    id: "plant-tree",
    theme: "environment",
    num: 6,
    title: "Everyone Must Plant One Tree",
    flavor: "Each citizen plants a tree before the day is out.",
    pressures: ["Environment", "Public space"],
    params: { mandatoryTree: true },
    push: { environment: 12 },
  },
  {
    id: "no-internet",
    theme: "culture",
    num: 7,
    title: "Nobody Can Use the Internet",
    flavor: "The networks go dark. Talk face to face.",
    pressures: ["Digital life", "Local ties"],
    params: { internet: false },
    push: { localism: 14, community: 4 },
  },
  {
    id: "learn-skill",
    theme: "culture",
    num: 8,
    title: "Everyone Must Learn One New Skill",
    flavor: "Every citizen learns something new before sundown.",
    pressures: ["Education", "Innovation"],
    params: { skillQuota: true },
    push: { learning: 12 },
  },
  {
    id: "no-private-property",
    theme: "money",
    num: 9,
    title: "No Private Property",
    flavor: "Homes and goods become shared. Nothing is 'mine'.",
    pressures: ["Ownership", "Housing"],
    params: { sharedProperty: true },
    push: { equality: 12, community: 4 },
    unlock: { key: "equality", min: 58, hint: "a city that grows more equal" },
  },
  {
    id: "tell-opinion",
    theme: "civic",
    num: 10,
    title: "Everyone Must Tell Their Opinion When Asked",
    flavor: "If someone asks what you think, you must answer.",
    pressures: ["Transparency", "Privacy"],
    params: { mustAnswer: true },
    push: { honesty: 8, participation: 6 },
    unlock: { key: "honesty", min: 56, hint: "a city that values honesty" },
  },
  {
    id: "no-advertising",
    theme: "culture",
    num: 11,
    title: "No Advertising",
    flavor: "Billboards come down. Commercials go silent.",
    pressures: ["Marketing", "Word of mouth"],
    params: { ads: false },
    push: { reputation: 8, localism: 6 },
  },
  {
    id: "hour-outside",
    theme: "wellbeing",
    num: 12,
    title: "Everyone Must Spend One Hour Outside",
    flavor: "At least an hour a day in public space.",
    pressures: ["Public space", "Health"],
    params: { outsideHour: true },
    push: { community: 8, leisure: 4 },
  },
  {
    id: "waste-tax",
    theme: "environment",
    num: 13,
    title: "Waste Is Taxed Heavily",
    flavor: "Every bag of trash comes with a steep bill.",
    pressures: ["Waste", "Product design"],
    params: { wasteTax: true },
    push: { environment: 10 },
    unlock: { key: "environment", min: 56, hint: "a city that cares about its environment" },
  },
  {
    id: "daily-vote",
    theme: "civic",
    num: 14,
    title: "Every Citizen Votes on Local Decisions Daily",
    flavor: "The city asks, and everyone decides.",
    pressures: ["Participation", "Attention"],
    params: { voting: true },
    push: { participation: 14 },
    unlock: { key: "community", min: 58, hint: "a strong community culture" },
  },
  {
    id: "reward-citizen",
    theme: "social",
    num: 15,
    title: "Every Citizen May Reward One Other Citizen per Day",
    flavor: "Give one symbolic reputation point to someone who earned it.",
    pressures: ["Recognition", "Status"],
    params: { rewards: true },
    push: { reputation: 12, generosity: 4 },
    unlock: { key: "generosity", min: 56, hint: "a generous city" },
  },

  // ---------- work ----------
  {
    id: "siesta",
    theme: "wellbeing",
    num: 16,
    title: "Everyone Takes an Afternoon Siesta",
    flavor: "From one to three, the city sleeps.",
    pressures: ["Rest", "Productivity"],
    params: {},
    push: { leisure: 10 },
    fx: {
      siesta: true,
      metric: { happiness: 2 },
      mood: 2,
      griev: { traits: { ambition: 0.55 }, groups: { commerce: 0.2, office: 0.15 } },
      emergent: {
        flag: "evening-city",
        hour: 17,
        headline: "THE CITY MOVES ITS CLOCK TO THE EVENING",
        body: "After a quiet afternoon, the streets fill late. Cafés are extending their hours and the dinner rush now starts after dark.",
        feed: "Rested residents are keeping the city lively into the evening.",
        label: "An evening culture emerged",
      },
      topics: ["shopVisits", "chat"],
    },
  },
  {
    id: "job-lottery",
    theme: "work",
    num: 17,
    title: "Jobs Are Assigned by Lottery",
    flavor: "Tomorrow's baker might be today's banker.",
    pressures: ["Merit", "Fairness"],
    params: {},
    push: { equality: 8, learning: 5 },
    unlock: { key: "equality", min: 56, hint: "a city obsessed with fairness" },
    fx: {
      beh: { teach: 2, argue: 1.2, help: 1.15 },
      econ: 0.93,
      metric: { equality: 4 },
      mood: -1,
      griev: { traits: { ambition: 0.35, productivity: 0.12 }, rich: 0.15 },
      emergent: {
        flag: "crash-courses",
        count: "teach",
        min: 8,
        headline: "NEW JOB, NO IDEA: CITY INVENTS THE FIVE-MINUTE CRASH COURSE",
        body: "Residents drawn into unfamiliar jobs are teaching each other on the spot. Accountants are learning to bake; bakers are learning spreadsheets.",
        feed: "Workers are teaching each other their new jobs.",
        label: "On-the-job crash courses spread",
      },
      topics: ["teach", "argue"],
    },
  },
  {
    id: "double-wage",
    theme: "work",
    num: 18,
    title: "The Minimum Wage Doubles",
    flavor: "Every hour of work is worth twice what it was.",
    pressures: ["Wages", "Prices"],
    params: {},
    push: { equality: 7 },
    fx: {
      wage: 1.35,
      price: 1.2,
      metric: { equality: 3, economy: -1 },
      mood: 1,
      griev: { groups: { commerce: 0.55 }, traits: { ambition: 0.2 }, rich: 0.15 },
      emergent: {
        flag: "self-checkout",
        count: "shopVisits",
        min: 30,
        headline: "SHOPS INSTALL SELF-CHECKOUTS AS WAGES CLIMB",
        body: "Workers have more to spend — and shops are spending on machines. The first self-checkout lanes appeared this afternoon.",
        feed: "Shops are automating their tills to handle higher wages.",
        label: "Shops automated their tills",
      },
      topics: ["shopVisits"],
    },
  },
  {
    id: "public-salaries",
    theme: "work",
    num: 19,
    title: "Every Salary Is Public",
    flavor: "Everyone's pay is posted in the city square.",
    pressures: ["Transparency", "Envy"],
    params: {},
    push: { honesty: 7, equality: 6 },
    unlock: { key: "honesty", min: 54, hint: "a city that tells the truth" },
    fx: {
      beh: { gossip: 1.6, argue: 1.15 },
      metric: { equality: 2 },
      griev: { traits: { privacy: 0.42 }, rich: 0.2 },
      emergent: {
        flag: "salary-talk",
        count: "gossip",
        min: 8,
        headline: "THE SALARY BOARD BECOMES THE CITY'S FAVORITE READING",
        body: "Crowds gather at the board every morning. Some raises are being demanded; some friendships are quietly ending.",
        feed: "Residents are comparing pay at the salary board.",
        label: "Pay transparency reshaped status",
      },
      topics: ["gossip", "argue"],
    },
  },

  // ---------- money ----------
  {
    id: "pay-what-you-want",
    theme: "money",
    num: 20,
    title: "Every Shop Is Pay-What-You-Want",
    flavor: "Take what you need. Pay what you think it's worth.",
    pressures: ["Trust", "Commerce"],
    params: {},
    push: { generosity: 8, reputation: 5 },
    fx: {
      price: 0.6,
      demand: 1.4,
      beh: { help: 1.15, crime: 0.8 },
      griev: { groups: { commerce: 0.6 }, traits: { ambition: 0.2 } },
      emergent: {
        flag: "honor-economy",
        count: "shopVisits",
        min: 40,
        headline: "THE HONOR ECONOMY: SHOPS PACKED, TILLS HALF-FULL",
        body: "Shoppers are pouring in. Some pay double to keep their favorite places alive; others pay in smiles. Shopkeepers are keeping a quiet list.",
        feed: "Shops are crowded under pay-what-you-want pricing.",
        label: "An honor economy formed",
      },
      topics: ["shopVisits", "help"],
    },
  },
  {
    id: "rent-cap",
    theme: "money",
    num: 21,
    title: "Rents Are Capped",
    flavor: "No home may cost more than a fair share of income.",
    pressures: ["Housing", "Landlords"],
    params: {},
    push: { equality: 8 },
    unlock: { key: "equality", min: 54, hint: "a city worried about the rent" },
    fx: {
      rent: 0.55,
      landValue: 0.985,
      migration: 1.15,
      metric: { equality: 3 },
      mood: 1,
      griev: { rich: 0.3, traits: { ambition: 0.12 } },
      emergent: {
        flag: "housing-queue",
        hour: 15,
        headline: "THE WAITLIST GROWS FOR THE CITY'S CHEAPEST HOMES",
        body: "Families from across the region want in. Landlords grumble about repairs; tenants say they can finally breathe.",
        feed: "A waiting list forms for rent-capped homes.",
        label: "Housing waitlists appeared",
      },
    },
  },
  {
    id: "screen-tax",
    theme: "culture",
    num: 22,
    title: "Screen Time Is Taxed",
    flavor: "Every hour on a screen costs a coin.",
    pressures: ["Digital life", "Attention"],
    params: {},
    push: { localism: 8, community: 5 },
    fx: {
      beh: { scroll: 0.3, chat: 1.35 },
      leisure: { home: -0.5, park: 0.5, community: 0.5 },
      griev: { traits: { curiosity: 0.2, privacy: 0.3 }, groups: { office: 0.2, creative: 0.2 } },
      emergent: {
        flag: "board-games",
        count: "chat",
        min: 35,
        headline: "BOARD GAME CAFÉS ARE THE NEW SOCIAL NETWORK",
        body: "Phones in pockets, residents rediscovered dice and cards. A board game café opened to a queue.",
        feed: "A board game café opens as screens go quiet.",
        label: "Board game cafés replaced feeds",
        business: { kind: "cafe", name: "Dice & Kettle", districts: ["oldtown", "university", "residential"] },
      },
      topics: ["scroll", "chat"],
    },
  },
  {
    id: "tourist-tax",
    theme: "money",
    num: 23,
    title: "Visitors Pay a Tourist Tax",
    flavor: "Every arriving traveler funds the city's parks.",
    pressures: ["Tourism", "Public funds"],
    params: {},
    push: { localism: 6, environment: 4 },
    unlock: { flag: "airport", hint: "a city with its own airport" },
    fx: {
      econ: 1.06,
      landValue: 1.01,
      metric: { environment: 2 },
      griev: { groups: { commerce: 0.35 } },
      emergent: {
        flag: "tourist-parks",
        hour: 14,
        headline: "TOURIST TAX PAYS FOR NEW PARK BENCHES",
        body: "The first receipts are in. Visitors grumble at the airport; residents enjoy freshly painted benches.",
        feed: "Tourist tax revenue is funding the parks.",
        label: "Tourists funded public space",
      },
    },
  },

  // ---------- social ----------
  {
    id: "shared-meal",
    theme: "social",
    num: 24,
    title: "Neighbors Share One Meal a Day",
    flavor: "Every table seats a stranger at dinner.",
    pressures: ["Community", "Privacy"],
    params: {},
    push: { community: 12 },
    fx: {
      beh: { chat: 1.6, help: 1.2 },
      leisure: { community: 1.5, home: -0.3 },
      mood: 1,
      griev: { traits: { privacy: 0.65 } },
      emergent: {
        flag: "street-tables",
        count: "communityVisits",
        min: 12,
        headline: "LONG TABLES TAKE OVER THE STREETS",
        body: "The community center ran out of chairs by six. Residents dragged tables into the street and kept going.",
        feed: "Shared dinners are spilling into the streets.",
        label: "Street dinners became tradition",
      },
      topics: ["chat", "communityVisits"],
    },
  },
  {
    id: "mentor-student",
    theme: "social",
    num: 25,
    title: "Every Adult Mentors a Student",
    flavor: "Knowledge passes hand to hand.",
    pressures: ["Education", "Time"],
    params: {},
    push: { learning: 10, generosity: 4 },
    fx: {
      beh: { teach: 3 },
      leisure: { library: 0.6 },
      skill: 0.03,
      griev: { traits: { curiosity: -0.3, ambition: 0.28 } },
      emergent: {
        flag: "mentor-web",
        count: "teach",
        min: 10,
        headline: "A CITY OF APPRENTICES",
        body: "Students are shadowing mechanics, nurses and chefs. Some have already been offered jobs.",
        feed: "Mentorships are turning into job offers.",
        label: "An apprenticeship culture formed",
      },
      topics: ["teach"],
    },
  },
  {
    id: "anonymous-city",
    theme: "social",
    num: 26,
    title: "Nobody Uses Their Real Name",
    flavor: "Everyone is anonymous in public.",
    pressures: ["Identity", "Accountability"],
    params: {},
    push: { honesty: -6, reputation: -6 },
    fx: {
      beh: { gossip: 1.8, argue: 1.4, help: 0.85, crime: 1.3 },
      metric: { trust: -3, safety: -2 },
      griev: { traits: { influence: 0.5, trust: 0.25 } },
      emergent: {
        flag: "masked-rumors",
        count: "gossip",
        min: 8,
        headline: "WHISPERS WITHOUT NAMES",
        body: "With nobody accountable, rumors travel faster than ever. A few residents say they finally feel free to speak.",
        feed: "Anonymous rumors are spreading quickly.",
        label: "Anonymity fueled rumors",
      },
      topics: ["gossip", "argue", "crime"],
    },
  },
  {
    id: "open-doors",
    theme: "social",
    num: 27,
    title: "No Door May Be Locked",
    flavor: "Homes, shops and offices stay open to all.",
    pressures: ["Trust", "Security"],
    params: {},
    push: { community: 7, generosity: 4 },
    unlock: { key: "community", min: 54, hint: "neighbors who trust each other" },
    fx: {
      beh: { help: 1.3, chat: 1.2, crime: 1.2 },
      metric: { safety: -2 },
      griev: { traits: { privacy: 0.4, trust: -0.15 }, rich: 0.2 },
      emergent: {
        flag: "open-house",
        count: "help",
        min: 18,
        headline: "OPEN HOUSES, OPEN HEARTS — AND A FEW MISSING BIKES",
        body: "Neighbors are wandering in to borrow sugar and staying for tea. A few items went missing; most came back with a note.",
        feed: "Unlocked doors are turning neighbors into regulars.",
        label: "An open-door culture formed",
      },
      topics: ["help", "crime"],
    },
  },

  // ---------- environment ----------
  {
    id: "green-roofs",
    theme: "environment",
    num: 28,
    title: "Every Roof Must Be Green",
    flavor: "Gardens on every rooftop by sundown.",
    pressures: ["Environment", "Construction"],
    params: {},
    push: { environment: 10 },
    unlock: { key: "environment", min: 54, hint: "a city that plants trees" },
    fx: {
      visual: "greenroofs",
      econ: 0.97,
      metric: { environment: 4 },
      mood: 1,
      griev: { rich: 0.3, groups: { commerce: 0.2, industry: 0.3 } },
      emergent: {
        flag: "rooftop-gardens",
        hour: 13,
        headline: "THE SKYLINE TURNS GREEN",
        body: "Rooftops across the city are sprouting gardens. Some are already growing tomatoes; the pigeons are delighted.",
        feed: "Rooftop gardens are spreading across the skyline.",
        label: "Rooftop gardens covered the city",
        worldFlag: "greenroofs",
      },
    },
  },
  {
    id: "no-cars",
    theme: "mobility",
    num: 29,
    title: "Private Cars Are Banned",
    flavor: "The streets belong to feet, bikes and buses.",
    pressures: ["Traffic", "Freedom"],
    params: {},
    push: { environment: 8, community: 4 },
    unlock: { key: "environment", min: 60, hint: "a truly green city" },
    fx: {
      cars: 0,
      bikes: 2.5,
      econ: 0.92,
      beh: { chat: 1.2 },
      leisure: { park: 0.6 },
      metric: { environment: 6, safety: 2 },
      griev: { groups: { industry: 0.5, commerce: 0.3 }, traits: { risk: 0.15 }, base: 0.1 },
      emergent: {
        flag: "street-play",
        count: "parkVisits",
        min: 25,
        headline: "EMPTY ROADS BECOME PLAYGROUNDS",
        body: "Without cars, children chalked hopscotch on the avenues and neighbors set out chairs. Delivery firms are scrambling for cargo bikes.",
        feed: "Car-free streets are filling with people.",
        label: "Streets became public space",
      },
      topics: ["parkVisits", "chat"],
    },
  },
  {
    id: "car-free-downtown",
    theme: "mobility",
    num: 30,
    title: "Downtown Goes Car-Free",
    flavor: "The city center is for pedestrians only.",
    pressures: ["Traffic", "Retail"],
    params: {},
    push: { localism: 6, environment: 4 },
    fx: {
      carFreeDowntown: true,
      cars: 0.7,
      bikes: 1.5,
      metric: { environment: 3, safety: 1 },
      leisure: { shop: 0.3, plaza: 0.3 },
      griev: { groups: { commerce: 0.3, office: 0.2 } },
      emergent: {
        flag: "pedestrian-core",
        count: "shopVisits",
        min: 30,
        headline: "FOOT TRAFFIC FLOODS THE CITY CENTER",
        body: "Shopkeepers who fought the ban are now putting tables on the pavement. Business is brisk.",
        feed: "The car-free center is drawing crowds of shoppers.",
        label: "Downtown became a pedestrian heart",
      },
      topics: ["shopVisits"],
    },
  },
  {
    id: "zero-plastic",
    theme: "environment",
    num: 31,
    title: "Single-Use Plastic Is Banned",
    flavor: "Bring your own bag, cup and box.",
    pressures: ["Waste", "Convenience"],
    params: {},
    push: { environment: 8 },
    fx: {
      beh: { litter: 0.35, recycle: 1.6, cleanup: 1.3 },
      price: 1.05,
      metric: { environment: 3 },
      griev: { groups: { industry: 0.4, commerce: 0.2 }, traits: { envConcern: -0.35 } },
      emergent: {
        flag: "refill-shops",
        count: "shopVisits",
        min: 25,
        headline: "REFILL STATIONS APPEAR ON EVERY CORNER",
        body: "Glass jars are the new status symbol. A refill shop opened and sold out of containers by noon.",
        feed: "A refill shop opens as plastic disappears.",
        label: "Refill culture spread",
        business: { kind: "shop", name: "The Refillery", districts: ["residential", "oldtown", "suburbs"] },
      },
      topics: ["litter", "recycle"],
    },
  },

  // ---------- mobility ----------
  {
    id: "free-transit",
    theme: "mobility",
    num: 32,
    title: "Public Transit Is Free",
    flavor: "Every metro ride costs nothing.",
    pressures: ["Mobility", "Public funds"],
    params: {},
    push: { equality: 5, community: 4 },
    unlock: { flag: "rail", hint: "a city with a metro line" },
    fx: {
      cars: 0.5,
      migration: 1.1,
      landValue: 1.01,
      econ: 1.03,
      metric: { environment: 3, equality: 2 },
      griev: { rich: 0.25, base: 0.05 },
      emergent: {
        flag: "packed-metro",
        hour: 9,
        headline: "STANDING ROOM ONLY ON THE METRO",
        body: "Ridership tripled overnight. Commuters who haven't taken a train in years are discovering the view from the loop.",
        feed: "The metro is packed after fares were abolished.",
        label: "The metro became the city's lifeline",
      },
    },
  },
  {
    id: "bike-friday",
    theme: "mobility",
    num: 33,
    title: "Everyone Travels by Bicycle",
    flavor: "No engines today — only pedals.",
    pressures: ["Health", "Distance"],
    params: {},
    push: { environment: 6, leisure: 3 },
    fx: {
      cars: 0.25,
      bikes: 4,
      metric: { environment: 3, happiness: 1 },
      griev: { traits: { productivity: 0.2 }, groups: { none: 0.35, industry: 0.2 } },
      emergent: {
        flag: "bike-repair",
        hour: 12,
        headline: "BIKE MECHANICS BECOME THE CITY'S BUSIEST WORKERS",
        body: "Flat tires everywhere. Neighbors are teaching each other to fix chains on the kerb.",
        feed: "Bike repair is booming.",
        label: "A cycling culture took root",
      },
    },
  },

  // ---------- civic ----------
  {
    id: "children-decide",
    theme: "civic",
    num: 34,
    title: "Children Write Today's Law",
    flavor: "The youngest citizens hold the pen for a day.",
    pressures: ["Participation", "Wisdom"],
    params: {},
    push: { participation: 8, leisure: 5 },
    fx: {
      leisure: { park: 1, plaza: 0.5 },
      mood: 2,
      econ: 0.95,
      griev: { traits: { ambition: 0.35 }, groups: { office: 0.2 }, base: 0.05 },
      emergent: {
        flag: "ice-cream-law",
        hour: 11,
        headline: "CHILDREN'S COUNCIL DECREES FREE ICE CREAM IN EVERY PARK",
        body: "The adults laughed — then lined up. Parks are fuller than on any day this year.",
        feed: "The children's council declared free ice cream.",
        label: "Children shaped civic life",
      },
      topics: ["parkVisits"],
    },
  },
  {
    id: "curfew",
    theme: "civic",
    num: 35,
    title: "Everyone Is Home by Ten",
    flavor: "A curfew falls over the city at 22:00.",
    pressures: ["Safety", "Nightlife"],
    params: {},
    push: { participation: -4 },
    fx: {
      curfew: 22,
      beh: { crime: 0.4 },
      metric: { safety: 5, happiness: -2 },
      griev: { traits: { risk: 0.45, curiosity: 0.25 }, groups: { student: 0.3, creative: 0.25 } },
      emergent: {
        flag: "secret-parties",
        hour: 21.5,
        headline: "BEHIND CLOSED DOORS, THE PARTIES CONTINUE",
        body: "Streets empty on the stroke of ten — but lights stay on in a lot of living rooms. Rumor says there's a speakeasy in Old Town.",
        feed: "Night life has moved behind closed doors.",
        label: "Nightlife went underground",
      },
      topics: ["crime"],
    },
  },
  {
    id: "open-borders",
    theme: "civic",
    num: 36,
    title: "Anyone May Move Here",
    flavor: "The city gates are open to all newcomers.",
    pressures: ["Growth", "Identity"],
    params: {},
    push: { localism: -6, learning: 5 },
    unlock: { key: "community", min: 56, hint: "a welcoming community" },
    fx: {
      migration: 1.6,
      landValue: 1.02,
      econ: 1.04,
      griev: { traits: { attachment: 0.45 }, base: 0.05 },
      emergent: {
        flag: "global-kitchen",
        hour: 13,
        headline: "NEW NEIGHBORS BRING NEW FLAVORS",
        body: "Newcomers opened a kitchen serving dishes from a dozen countries. The queue wrapped around the block.",
        feed: "Newcomers open the Global Kitchen.",
        label: "Newcomers reshaped the city",
        business: { kind: "restaurant", name: "Global Kitchen", districts: ["downtown", "oldtown", "residential"] },
      },
    },
  },

  // ---------- culture ----------
  {
    id: "public-art",
    theme: "culture",
    num: 37,
    title: "Every Wall Gets a Mural",
    flavor: "Artists are handed the city's walls.",
    pressures: ["Culture", "Property"],
    params: {},
    push: { community: 6, leisure: 4 },
    fx: {
      visual: "murals",
      beh: { chat: 1.2 },
      metric: { happiness: 2 },
      mood: 1,
      griev: { rich: 0.35, traits: { privacy: 0.2 } },
      emergent: {
        flag: "mural-city",
        hour: 12,
        headline: "THE CITY BECOMES A GALLERY",
        body: "Blank walls are blooming with color. Tourists are already taking photos of the fish mural in the harbor.",
        feed: "Murals are appearing across the city.",
        label: "The city became a gallery",
        worldFlag: "murals",
      },
      topics: ["chat"],
    },
  },
  {
    id: "quiet-nights",
    theme: "wellbeing",
    num: 38,
    title: "Silence After Nine",
    flavor: "No noise in public after 21:00.",
    pressures: ["Rest", "Nightlife"],
    params: {},
    push: { leisure: 5 },
    fx: {
      curfew: 21.5,
      beh: { argue: 0.7 },
      mood: 1,
      metric: { happiness: 1 },
      griev: { traits: { risk: 0.3 }, groups: { student: 0.35, creative: 0.3 } },
      emergent: {
        flag: "whisper-cafes",
        hour: 21,
        headline: "WHISPER CAFÉS AND EARLY NIGHTS",
        body: "Streets go hushed at nine. Residents say they're sleeping better than they have in years.",
        feed: "The city goes quiet at nine.",
        label: "The city learned to rest",
      },
    },
  },
  {
    id: "day-of-rest",
    theme: "wellbeing",
    num: 39,
    title: "Shops Close for a Day of Rest",
    flavor: "No buying or selling — only resting.",
    pressures: ["Commerce", "Family time"],
    params: {},
    push: { leisure: 8, community: 6 },
    fx: {
      demand: 0.35,
      econ: 0.93,
      leisure: { park: 1.5, community: 1, shop: -1.5 },
      metric: { happiness: 2 },
      mood: 1,
      griev: { groups: { commerce: 0.6 }, traits: { ambition: 0.2 } },
      emergent: {
        flag: "picnic-day",
        count: "parkVisits",
        min: 25,
        headline: "A CITY-WIDE PICNIC",
        body: "With the shops shut, families spread blankets in every park. The grocery was the only queue in town.",
        feed: "The whole city is picnicking.",
        label: "A day of rest became tradition",
      },
      topics: ["parkVisits", "shopVisits"],
    },
  },
  {
    id: "free-university",
    theme: "culture",
    num: 40,
    title: "University Is Free for Everyone",
    flavor: "Any citizen, any age, any course.",
    pressures: ["Education", "Public funds"],
    params: {},
    push: { learning: 12 },
    unlock: { key: "learning", min: 56, hint: "a city hungry to learn" },
    fx: {
      beh: { teach: 1.5, learn: 1.5 },
      leisure: { library: 1.2 },
      skill: 0.05,
      migration: 1.05,
      griev: { rich: 0.2, traits: { curiosity: -0.2 }, base: 0.15 },
      emergent: {
        flag: "lecture-halls",
        count: "libraryVisits",
        min: 10,
        headline: "GRANDPARENTS ENROLL IN PHYSICS",
        body: "The university's lecture halls are overflowing with every generation. The library has started opening at dawn.",
        feed: "Residents of every age are enrolling at university.",
        label: "Lifelong learning took hold",
      },
      topics: ["teach"],
    },
  },
];

export const THEME_LABEL: Record<RuleTheme, string> = {
  work: "Work",
  money: "Money",
  social: "Social",
  environment: "Environment",
  mobility: "Mobility",
  civic: "Civic",
  culture: "Culture",
  wellbeing: "Wellbeing",
};

export const fxOf = (id: RuleId | null): RuleFx | null => (id ? ruleById(id).fx ?? null : null);

export const ruleById = (id: RuleId): RuleDef => RULES.find((r) => r.id === id)!;

export function paramsFor(rule: RuleId | null): Params {
  return rule ? { ...DEFAULT_PARAMS, ...ruleById(rule).params } : { ...DEFAULT_PARAMS };
}

export interface Combo {
  id: string;
  rules: [RuleId, RuleId];
  headline: string;
  body: string;
  label: string;
  push: Partial<Record<CultureKey, number>>;
}

export const COMBOS: Combo[] = [
  {
    id: "reputation-marketing",
    rules: ["no-advertising", "reward-citizen"],
    headline: "REPUTATION BECOMES THE NEW MARKETING",
    body: "With ads gone and rewards flowing, businesses now court the city's most-rewarded residents. A recommendation from the right person is worth more than any billboard ever was.",
    label: "Reputation became marketing",
    push: { reputation: 10 },
  },
  {
    id: "reputation-currency",
    rules: ["no-money", "reward-citizen"],
    headline: "REPUTATION BECOMES CURRENCY",
    body: "Reward points are being traded for bread, repairs and favors. Without money, standing in the community is the only balance that counts.",
    label: "Reputation became currency",
    push: { reputation: 12, equality: -4 },
  },
  {
    id: "park-life",
    rules: ["plant-tree", "hour-outside"],
    headline: "THE CITY MOVES OUTDOORS",
    body: "New trees and a daily hour outside have turned the parks into the city's living room. Cafés are setting up tables under the canopy.",
    label: "Parks became the center of public life",
    push: { community: 8, environment: 6 },
  },
  {
    id: "radical-sincerity",
    rules: ["no-lying", "help-stranger"],
    headline: "RADICAL SINCERITY: HELP YOU CAN TRUST",
    body: "When nobody may lie, a favor can't be faked. Residents say help feels different when you know it's meant.",
    label: "Sincere help culture formed",
    push: { honesty: 6, generosity: 6 },
  },
  {
    id: "town-hall",
    rules: ["no-internet", "daily-vote"],
    headline: "THE TOWN HALL IS BACK",
    body: "With no screens to vote on, residents are gathering in person to decide. The city hall steps have become the city's forum.",
    label: "In-person democracy revived",
    push: { participation: 10, localism: 6 },
  },
  {
    id: "academies",
    rules: ["four-hour-day", "learn-skill"],
    headline: "AFTERNOONS BECOME NEIGHBORHOOD ACADEMIES",
    body: "Short workdays plus a learning quota have filled the afternoons with classes taught by neighbors, for neighbors.",
    label: "Neighborhood academies emerged",
    push: { learning: 10, community: 4 },
  },
  {
    id: "commons",
    rules: ["no-private-property", "basic-income"],
    headline: "A CITY OF COMMONS",
    body: "Shared homes and equal incomes are blurring the line between 'mine' and 'ours'. Some thrive in it; others quietly miss having a door they can lock.",
    label: "A commons economy emerged",
    push: { equality: 10, community: 4 },
  },
  {
    id: "repair-culture",
    rules: ["waste-tax", "learn-skill"],
    headline: "EVERYONE'S A FIXER NOW",
    body: "Taxed waste and a skill a day have produced a city of tinkerers. Broken things are becoming lessons instead of trash.",
    label: "Repair culture took hold",
    push: { environment: 6, learning: 6 },
  },
];
